# Generated by Django 3.1.5 on 2021-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('oname', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
