# Generated by Django 3.1.5 on 2021-01-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='uploads/ids/'),
        ),
    ]
