# Generated by Django 3.1.2 on 2021-01-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210119_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
