# Generated by Django 3.1.2 on 2021-01-19 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210119_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
