# Generated by Django 3.1.2 on 2021-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customer_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
