# Generated by Django 3.1.2 on 2021-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210119_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
