# Generated by Django 3.1.2 on 2021-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
