# Generated by Django 3.1.2 on 2021-01-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
    ]
