# Generated by Django 3.1.2 on 2021-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_category_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='uploads/products/'),
        ),
    ]
