# Generated by Django 3.1.5 on 2021-01-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Menu',
            new_name='menu',
        ),
    ]
