# Generated by Django 3.1.2 on 2021-01-22 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210122_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takeaway',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
